package Gui;

import entidades.Libros;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        setLocationRelativeTo(null);
        this.setSize(1100, 650);//forzar dimension
        setResizable(false);//no se podra redimensionar
        
        PHome p1 = new PHome();
        ShowPanel(p1);
        
        SetDate();
    }
    
    private void SetDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("EEEE, dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPrincipal = new javax.swing.JPanel();
        bgBotones = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnCata = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        bgPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgBotones.setBackground(new java.awt.Color(153, 0, 0));
        bgBotones.setMinimumSize(new java.awt.Dimension(244, 650));
        bgBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(118, 0, 0));
        btnHome.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        btnHome.setText("HOME LIBRERÍA");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIconTextGap(6);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        bgBotones.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 64));

        btnAgregar.setBackground(new java.awt.Color(118, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/libro.png"))); // NOI18N
        btnAgregar.setText("AGREGAR LIBRO");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.setIconTextGap(6);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        bgBotones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 64));

        btnCata.setBackground(new java.awt.Color(118, 0, 0));
        btnCata.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCata.setForeground(new java.awt.Color(255, 255, 255));
        btnCata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cata.png"))); // NOI18N
        btnCata.setText("CATÁLOGO");
        btnCata.setBorder(null);
        btnCata.setBorderPainted(false);
        btnCata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCata.setIconTextGap(6);
        btnCata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCataActionPerformed(evt);
            }
        });
        bgBotones.add(btnCata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 64));

        btnSalir.setBackground(new java.awt.Color(118, 0, 0));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(212, 175, 55));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        bgBotones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 64));

        jSeparator1.setForeground(new java.awt.Color(212, 175, 55));
        bgBotones.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 50, 10));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo_3.png"))); // NOI18N
        jLabel1.setText("logo aplicacion");
        bgBotones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 170));

        btnInfo.setBackground(new java.awt.Color(118, 0, 0));
        btnInfo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/info.png"))); // NOI18N
        btnInfo.setText("INFORMACIÓN");
        btnInfo.setBorder(null);
        btnInfo.setBorderPainted(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInfo.setIconTextGap(6);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        bgBotones.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 64));

        bgPrincipal.add(bgBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));
        bgPrincipal.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 870, 560));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("{dayname}, {day} de {month} de {year}");
        jPanel1.add(dateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 50));

        bgPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 870, 90));

        getContentPane().add(bgPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        PHome p1 = new PHome();
        p1.setSize(870, 560);//forzar dimension
        p1.setLocation(0, 0);
        
        //pagina inicial
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);//Cerrar programa
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        PAgregar p3 = new PAgregar();
        p3.setSize(870, 560);//forzar dimension
        p3.setLocation(0, 0);
        
        content.removeAll();
        content.add(p3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCataActionPerformed
        PCatalogo p2 = new PCatalogo();
        p2.setSize(870, 560);//forzar dimension
        p2.setLocation(0, 0);
        
        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCataActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        PInfo p4 = new PInfo();
        p4.setSize(870, 560);//forzar dimension
        p4.setLocation(0, 0);

        content.removeAll();
        content.add(p4, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();    
    }//GEN-LAST:event_btnInfoActionPerformed

    //creo un metodo para mostrar panel
    private void ShowPanel(JPanel p){
        p.setSize(870, 560);//forzar dimension
        p.setLocation(0, 0);
        
        //pagina inicial
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgBotones;
    private javax.swing.JPanel bgPrincipal;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCata;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
